"""initial EarningsOS schema

Revision ID: a3b25cd8ea97
Revises: 
Create Date: 2026-09-12 06:58:10.074240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3b25cd8ea97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_key', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('pretrained_only', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key')
    )
    op.create_table('stocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('earnings_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eps_actual', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('eps_estimate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('revenue_actual', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('revenue_estimate', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('guidance_text', sa.Text(), nullable=True),
    sa.Column('concall_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_events_event_date'), 'earnings_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_earnings_events_stock_id'), 'earnings_events', ['stock_id'], unique=False)
    op.create_table('intelligence_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon', sa.String(length=50), nullable=False),
    sa.Column('signal', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_signals_as_of'), 'intelligence_signals', ['as_of'], unique=False)
    op.create_index(op.f('ix_intelligence_signals_stock_id'), 'intelligence_signals', ['stock_id'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_model_id'), 'model_runs', ['model_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_content_hash'), 'news_articles', ['content_hash'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_stock_id'), 'news_articles', ['stock_id'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('traded_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'interval', 'timestamp', 'source', name='uq_price_bar')
    )
    op.create_index(op.f('ix_price_bars_stock_id'), 'price_bars', ['stock_id'], unique=False)
    op.create_index(op.f('ix_price_bars_timestamp'), 'price_bars', ['timestamp'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=False),
    sa.Column('stock_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon', sa.String(length=50), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('direction', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_model_run_id'), 'forecasts', ['model_run_id'], unique=False)
    op.create_index(op.f('ix_forecasts_stock_id'), 'forecasts', ['stock_id'], unique=False)
    op.create_index(op.f('ix_forecasts_target_time'), 'forecasts', ['target_time'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('positive_probability', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('negative_probability', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('neutral_probability', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_scores_article_id'), 'sentiment_scores', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_scores_article_id'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_forecasts_target_time'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_stock_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_model_run_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_price_bars_timestamp'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_stock_id'), table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index(op.f('ix_news_articles_stock_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_content_hash'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_model_runs_model_id'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_intelligence_signals_stock_id'), table_name='intelligence_signals')
    op.drop_index(op.f('ix_intelligence_signals_as_of'), table_name='intelligence_signals')
    op.drop_table('intelligence_signals')
    op.drop_index(op.f('ix_earnings_events_stock_id'), table_name='earnings_events')
    op.drop_index(op.f('ix_earnings_events_event_date'), table_name='earnings_events')
    op.drop_table('earnings_events')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
